/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tLight_templ.c => src/tLight.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * eprpcd           uint8_t          ATTR_eprpcd     
 * eprpatr          ATR              ATTR_eprpatr    
 * eprpsz           uint8_t          ATTR_eprpsz     
 * exinf            intptr_t         ATTR_exinf      
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tLight_tecsgen.h"
#include "tEchonet_tecsgen.h"
#include "echonet_cfg.h"
#include "gpio_api.h"
#include "kernel_cfg.h"


#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif



gpio_t pow_led;
/* リレー出力 */
gpio_t relay_sw;
/* カラーLED */
gpio_t led_blue, led_green, led_red;
/* ユーザースイッチ CN16-4 */
gpio_t sw1, sw2;


/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eLight
 * entry port: eLight
 * signature:  sLight
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eLight_onOffPropertySet
 * name:         eLight_onOffPropertySet
 * global_name:  tLight_eLight_onOffPropertySet
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eLight_onOffPropertySet(CELLIDX idx, const uint8_t* src, int size, bool_t* anno)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	/* サイズが１以外は受け付けない */
	if (size != 1)
		return 0;

	*anno = *((uint8_t *)ATTR_exinf) != *((uint8_t *)src);

    //syslog(LOG_NOTICE,"src %x", *(uint8_t *) src); //
	switch (*(uint8_t *)src) {

	/* ONの場合 */
	case 0x30:
		*((uint8_t *)ATTR_exinf) = *((uint8_t *)src);
		/* LEDをON */
		gpio_write(&pow_led, 1);
		/* リレー出力をON */
		gpio_write(&relay_sw, 1);
		syslog(LOG_NOTICE,"led on"); //

		break;
	/* OFFの場合 */
	case 0x31:
		*((uint8_t *)ATTR_exinf) = *((uint8_t *)src);
		/* LEDをOFF */
		gpio_write(&pow_led, 0);
		/* リレー出力をOFF */
		gpio_write(&relay_sw, 0);
		syslog(LOG_NOTICE,"led off"); //
		break;
	/* 0x30か0x31以外は受け付けない */
	default:

		syslog(LOG_NOTICE,"led default"); //
		return 0;
	}

	return 1;
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/

/* #[<ENTRY_FUNC>]# eLight_OnPropertySet
 * name:         eLight_OnPropertySet
 * global_name:  tLight_eLight_OnPropertySet
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eLight_OnPropertySet(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
	gpio_write(&pow_led, 1);
	gpio_write(&relay_sw, 1);
	syslog(LOG_NOTICE, "LED on");
	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eLight_OffPropertySet
 * name:         eLight_OffPropertySet
 * global_name:  tLight_eLight_OffPropertySet
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eLight_OffPropertySet(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
	gpio_write(&pow_led, 0);
	gpio_write(&relay_sw, 0);
	syslog(LOG_NOTICE, "LED off");
	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
